### ISSUE TITLE
bug: [ERRO] address is listened:0.0.0.0:80

### ISSUE THREAD

**Issue by liudonghua123** [eolinker/apinto#95]
### Current Behavior

I followed the instructions on https://help.apinto.com/docs/apinto/quick/arrange.html, and when I execute `./apinto start`, I got `[ERRO] address is listened:0.0.0.0:80` error. and I checked the configs in `config.yml.tpl` or https://help.apinto.com/docs/apinto/quick/quick_course.html#%E4%BD%BF%E7%94%A8%E6%AD%A5%E9%AA%A4.
I could not found any configs around `:80`.

```
[root@localhost apinto]# cat config.yml.tpl 
version: 2
#certificate: # 证书存放根目录
#  dir: /etc/apinto/cert
client:
  #advertise_urls: # open api 服务的广播地址
  #- http://127.0.0.1:9400
  listen_urls: # open api 服务的监听地址
    - http://0.0.0.0:9400
  #certificate:  # 证书配置，允许使用ip的自签证书
  #  - cert: server.pem
  #    key: server.key
gateway:
  #advertise_urls: # 转发服务的广播地址
  #- http://127.0.0.1:9400
  listen_urls: # 转发服务的监听地址
    - https://0.0.0.0:8099
    - http://0.0.0.0:8099
peer: # 集群间节点通信配置信息
  listen_urls: # 节点监听地址
    - http://0.0.0.0:9401
  #advertise_urls: # 节点通信广播地址
  # - http://127.0.0.1:9400
  #certificate:  # 证书配置，允许使用ip的自签证书
  #  - cert: server.pem
  #    key: server.key

[root@localhost apinto]#
```

### Expected Behavior

The listen port of `./apinto start` could be config.

### Error Logs

bug: [ERRO] address is listened:0.0.0.0:80

### Steps to Reproduce

1. download apinto_v0.12.1_linux_amd64.tar.gz and extracted it.
2. execute `./apinto start`

### Environment

- APINTO version (run `apinto version`):

```
[root@localhost apinto]# ./apinto version
Apinto version: 0.12.1
Golang version: go version go1.19.4 linux/amd64
Git commit hash: 68da18d234080b71fa70fe1cd0cee3933f6bbf28
Built on: 2023-03-03T13:27:58Z
Built by: goreleaser
Built by eosc version: v0.11.0
[root@localhost apinto]#
```

- Operating system (run `uname -a`):

```
[root@localhost apinto]# uname -a
Linux localhost.localdomain 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost apinto]# 
```

**Comment by liudonghua123** [comment]
I copied config.yml.tpl to config.yml via `cp config.yml.tpl config.yml` and then execute `./apinto start`, not it works.

Why not use the default listening ports configgured in `config.yml.tpl`.

**Comment by Dot-Liu** [comment]
This is not a bug. It is related to the configuration of the apito. yml file. The configuration of apito. yml reads the/etc/apito/config.yml file by default.

**Comment by liudonghua123** [comment]
But I have not `/etc/apito/config.yml` file. Where is 'listen: 80' configured?

**Comment by Dot-Liu** [comment]
The default port is 80. You can directly modify the config configuration of `apinto.yml`
![image](https://user-images.githubusercontent.com/14105999/223315018-7d8725b7-2baa-4c19-9a22-dc3ff536ee53.png)

**Comment by liudonghua123** [comment]
I followed the guidance on https://help.apinto.com/docs/apinto/quick/arrange.html#%E4%B8%8B%E8%BD%BD%E5%AE%98%E6%96%B9%E6%8F%90%E4%BE%9B%E7%9A%84%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85-%E6%8E%A8%E8%8D%90. 

I got this error when I execute `./apinto start`. Then I copied the config.yml.tpl to config.yml in the directory of `apinto`, and tried again without this errors. 

I did not have `apinto.yml` in the cwd, only apinto.yml.tpl exists there.


```
[root@localhost apinto]# cat config.yml
version: 2
#certificate: # 证书存放根目录
#  dir: /etc/apinto/cert
client:
  #advertise_urls: # open api 服务的广播地址
  #- http://127.0.0.1:9400
  listen_urls: # open api 服务的监听地址
    - http://0.0.0.0:9400
  #certificate:  # 证书配置，允许使用ip的自签证书
  #  - cert: server.pem
  #    key: server.key
gateway:
  #advertise_urls: # 转发服务的广播地址
  #- http://127.0.0.1:9400
  listen_urls: # 转发服务的监听地址
    - https://0.0.0.0:8099
    - http://0.0.0.0:8099
peer: # 集群间节点通信配置信息
  listen_urls: # 节点监听地址
    - http://0.0.0.0:9401
  #advertise_urls: # 节点通信广播地址
  # - http://127.0.0.1:9400
  #certificate:  # 证书配置，允许使用ip的自签证书
  #  - cert: server.pem
  #    key: server.key

[root@localhost apinto]# cat apinto.yml.tpl 
# 数据文件放置目录
data_dir: /var/lib/apinto

# pid文件放置地址
pid_dir: /var/run/apinto/

# 日志放置目录
log_dir: /var/log/apinto

# socket放置目录
socket_dir: /tmp/apinto

# apinto运行配置地址
config: /etc/apinto/config.yml

# 扩展仓库目录
extends_dir: /var/lib/apinto/extenders/

# 错误日志文件名
error_log_name:  error.log

# 错误日志等级
error_log_level: error

# 错误日志过期时间，默认单位为天，d|天，h|小时
error_log_expire: 7d

# 错误日志切割周期，仅支持day、hour
error_log_period: day
[root@localhost apinto]#
```

Does the listen configuration located in `client.listen_urls`?
